apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production-1
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  orphanedResources:
    warn: false
  sourceRepos:
    - '*'
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: develop-1
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  orphanedResources:
    warn: false
  sourceRepos:
    - '*'
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-project-1
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  orphanedResources:
    warn: false
  sourceRepos:
    - '*'
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack-test-116
spec:
  project: production
  source:
    repoURL: 'https://github.com/jeeeepp/argocd-example.git'
    path: helm-guestbook
    targetRevision: HEAD
  destination:
    server: 'https://172.29.47.116:57830'
    namespace: prod
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack-test-in-cluster
spec:
  project: develop
  source:
    repoURL: 'https://github.com/jeeeepp/argocd-example.git'
    path: helm-guestbook
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack-sample-in-cluster
spec:
  project: develop
  source:
    repoURL: 'https://github.com/jeeeepp/argocd-example.git'
    path: helm-guestbook/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated: {}
