apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jeeeepp/argocd-in-argocd.git'
    path: application-project
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: {}
